package model;


public class CacMonHoc {
    public CacMonHoc()
    {
        
    }
    public String[] IT_TienTrinh = {
            "Triet hoc Mac-Lenin",
"Giai tich 1",
"Tin hoc co so 1",
"Dai so",
"Kinh te chinh tri Mac-Lenin",
"Tieng anh Course 1",
"Giai tich 2",
"Vat ly ung dung",
"Tin hoc co so 2",
"Ky thuat so",
"Phap luat dai cuong",
"Chu nghia xa hoi khoa hoc",
"Tieng anh Course 2",
"Toan roi rac 1",
"Xu ly tin hieu so",
"Ngon ngu lap trinh C++",
"Xac suat thong ke",
"Ky nang mem 1",
"Tu tuong Ho Chi Minh",
"Tieng anh Course 3",
"Kien truc may tinh",
"Toan roi rac 2",
"Cau truc du lieu va giai thuat",
"Ly thuyet thong tin",
"Ky nang mem 2",
"Lich su Dang Cong San Viet Nam",
"Lap trinh voi Python",
"He dieu hanh",
"Mang may tinh",
"Lap trinh huong doi tuong",
"Co so du lieu",
"Tieng anh Course 3+",
"Lap trinh web",
"An toan va bao mat he thong thong tin",
"Nhap mon cong nghe phan mem",
"Nhap mon tri tue nhan tao",
"Co so du lieu phan tan",
"Thuc tap co so",
"Quan ly du an phan mem",
"Phat trien cac he thong thong minh",
"Xu ly anh",
"Phan tich va thiet ke HTTT",
"IOT va ung dung",
"Hoc phan tu chon",
"Phuong phap luan NCKH",
"Dam bao chat luong phan mem",
"Phat trien phan mem huong dich vu",
"Phat trien ung dung cho cac thiet bi di dong",
"Kien truc va thiet ke phan mem",
"Xay dung cac he thong nhung",
"Chuyen de Cong nghe phan mem"
        };
        public String[] BC_TienTrinh = {
    "Triet hoc Mac-Lenin",
"Co so ly luan bao chi truyen thong",
"Phuong phap luan NCKH",
"Co so van hoa Viet Nam",
"Tin hoc co so 1",
"Kinh te chinh tri Mac-Lenin",
"Tieng anh Course 1",
"Van hoa va truyen thong dai chung",
"Logic hoc dai cuong",
"Tam ly hoc bao chi",
"Tieng Viet thuc hanh",
"My thuat dai cuong",
"Tin hoc co so 3",
"Chu nghia xa hoi khoa hoc",
"Phap luat, Dao duc va Lao dong bao chi",
"Tieng anh Course 2",
"Cac loai hinh bao chi",
"Nhap mon thiet ke va su sang tao trong bao chi",
"Nhiep anh bao chi",
"Nhap mon cong nghe bao chi so",
"Tu tuong Ho Chi Minh",
"Tieng anh Course 3",
"Ngon ngu bao chi va sang tao tac pham bao chi",
"Thiet ke do hoa bao chi",
"Ky thuat Quay va dung video",
"Kich ban cho tac pham bao chi so",
"Tieng anh Course 3+",
"Kinh te bao chi",
"Thuong hieu va xay dung thuong hieu trong bao chi",
"Cong cu xu ly hieu ung trong bao chi so",
"Bao chi du lieu",
"Lich su Dang Cong San Viet Nam",
"Nghe thuat chu ",
"Bao chi va phuong tien truyen thong XH",
"Internet va cong nghe web",
"Thiet ke minh hoa trong bao chi so",
"Viet chuyen nghiep",
"Thu thap va xu ly du lieu bao chi so",
"3 Hoc phan tu chon",
"Dan chuong trinh",
"Van hanh toa soan bao chi so",
"Cong nghe AI trong phan tich du lieu bao chi so",
"Bao chi va du luan xa hoi",
"Bao chi duong dai",
"3 Hoc phan tu chon",
"Thuc tap va tot nghiep "
};
        public String[] KHMT_TienTrinh = {
    "Triet hoc Mac-Lenin",
"Giai tich 1",
"Tin hoc co so 1",
"Dai so",
"Kinh te chinh tri Mac-Lenin",
"Tieng anh Course 1",
"Vat ly 1 va thi nghiem",
"Giai tich 2",
"Tin hoc co so 2",
"Ky thuat so",
"Xac suat thong ke",
"Chu nghia xa hoi khoa hoc",
"Tieng anh Course 2",
"Vat ly 3 va thi nghiem",
"Toan roi rac 1",
"Ngon ngu C++",
"Xu ly tin hieu so",
"Tu tuong Ho Chi Minh",
"Tieng anh Course 3",
"Kien truc may tinh",
"Toan roi rac 2",
"Cau truc du lieu va giai thuat",
"Ly thuyet thong tin",
"Lich su Dang Cong San Viet Nam",
"Tieng anh Course 3+",
"He dieu hanh",
"Lap trinh voi python",
"Lap trinh huong doi tuong",
"Mang may tinh",
"Co so du lieu",
"Nhap mon tri tue nhan tao",
"An toan va bao mat he thong thong tin",
"Nhap mon cong nghe phan mem",
"Lap trinh web",
"He quan tri co so du lieu",
"Thuc tap co so",
"Phuong phap luan NCKH",
"Xu ly anh",
"Hoc may",
"Phan tich va thiet ke HTTT",
"Nhap hoc khoa hoc du lieu",
"Hoc phan tu chon",
"Nhap mon hoc sau",
"Khai pha du lieu lon",
"Hoc phan tu chon 1",
"Hoc phan tu chon 2",
"Hoc phan tu chon 3",
"Hoc phan tu chon 4"
};
        public String[] QT_TienTrinh  = {
    "Triet hoc Mac-Lenin",
"Tam ly quan ly",
"Tin hoc co so 1",
"Toan cao cap 1",
"Phap luat dai cuong",
"Kinh te chinh tri Mac-Lenin",
"Tieng Anh (Course 1)",
"Toan cao cap 2",
"Ly thuyet xac suat va thong ke",
"Tin hoc co so 3",
"Kinh te vi mo 1",
"Chu nghia xa hoi khoa hoc",
"Tieng Anh (Course 2)",
"Toan kinh te",
"Kinh te vi mo 1",
"Marketing can ban",
"Quan tri hoc",
"Lich su Dang cong san Viet Nam",
"Tieng Anh (Course 3)",
"Nguyen ly ke toan",
"Tai chinh tien te",
"Giao tiep trong kinh doanh",
"Thuong mai dien tu can ban",
"Kinh te luong",
"Tu tuong Ho Chi Minh",
"Tieng Anh (Course 3 Plus)",
"Quan tri san xuat",
"Thong ke doanh nghiep",
"Logistics can ban",
"He thong thong tin quan ly",
"Quan tri chien luoc",
"Quan tri tai chinh doanh nghiep",
"Ke toan quan tri",
"Luat kinh doanh",
"Quan tri ban hang va phan phoi san pham",
"Quan tri nhan luc",
"Phan tich hoat dong san xuat kinh doanh",
"2 hoc phan tu chon",
"Phuong phap luan NCKH",
"Quan tri marketing",
"Khoi su kinh doanh",
"Quan tri doanh nghiep",
"Kinh doanh quoc te",
"Quan tri doi moi sang tao",
"2 hoc phan tu chon",
"Thuc tap va tot nghiep "
};
        public String[] MK_TienTrinh = {
    "Triet hoc Mac-Lenin",
"Tam ly quan ly",
"Tin hoc co so 1",
"Toan cao cap 1",
"Phap luat dai cuong",
"Kinh te chinh tri Mac-Lenin",
"Tieng Anh (Course 1)",
"Toan cao cap 2",
"Ly thuyet xac suat va thong ke",
"Tin hoc co so 3",
"Kinh te vi mo 1",
"Chu nghia xa hoi khoa hoc",
"Tieng Anh (Course 2)",
"Toan kinh te",
"Kinh te vi mo 1",
"Marketing can ban",
"Tu tuong Ho Chi Minh",
"Tieng Anh (Course 3)",
"Nguyen ly ke toan",
"Quan tri hoc",
"Hanh vi khach hang",
"Quan tri Marketing",
"Internet va ung dung trong kinh doanh",
"Lich su Dang cong san VN",
"Tieng Anh (Course 3 Plus)",
"Kinh te luong",
"Cac he thong thong tin trong DN",
"Quan ly du an",
"Marketing dich vu",
"Thuong mai dien tu",
"Phat trien va ung dung web trong Marketing",
"Phuong phap nghien cuu Marketing",
"Marketing cong nghiep",
"Ung dung DPT trong kinh doanh",
"Truyen thong Marketing tich hop",
"Quan tri co so du lieu kinh doanh",
"E-Marketing",
"03 hoc phan tu chon",
"Phuong phap luan NCKH",
"Phan tich web",
"Marketing qua phuong tien truyen thong XH",
"Tong quan ve bien tap web",
"Marketing bang cong cu tim kiem",
"De an: Ke hoach Internet Marketing",
"Thuc tap va tot nghiep "
};

}
